### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by jschouwstra** [ionic-team/tutorial-photo-gallery-vue#11]
When I run ionic serve inside your project I get this error:

> ionic serve
> vue-cli-service serve
[vue-cli-service]  INFO  Starting development server...
[vue-cli-service] (node:17247) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
[vue-cli-service] (Use `node --trace-deprecation ...` to show where the warning was created)
[vue-cli-service] node:internal/crypto/hash:67
[vue-cli-service]   this[kHandle] = new _Hash(algorithm, xofLen);
[vue-cli-service]                   ^
[vue-cli-service] Error: error:0308010C:digital envelope routines::unsupported
[vue-cli-service]     at new Hash (node:internal/crypto/hash:67:19)
[vue-cli-service]     at Object.createHash (node:crypto:130:10)
[vue-cli-service]     at module.exports (/private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/webpack/lib/util/createHash.js:135:53)
[vue-cli-service]     at NormalModule._initBuildHash (/private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/webpack/lib/NormalModule.js:417:16)
[vue-cli-service]     at handleParseError (/private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/webpack/lib/NormalModule.js:471:10)
[vue-cli-service]     at /private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/webpack/lib/NormalModule.js:503:5
[vue-cli-service]     at /private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/webpack/lib/NormalModule.js:358:12
[vue-cli-service]     at /private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[vue-cli-service]     at iterateNormalLoaders (/private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[vue-cli-service]     at Array.<anonymous> (/private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[vue-cli-service]     at Storage.finished (/private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
[vue-cli-service]     at /private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
[vue-cli-service]     at /private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/graceful-fs/graceful-fs.js:123:16
[vue-cli-service]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
[vue-cli-service]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[vue-cli-service]   library: 'digital envelope routines',
[vue-cli-service]   reason: 'unsupported',
[vue-cli-service]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[vue-cli-service] }
[vue-cli-service] Node.js v17.2.0
[vue-cli-service] node:internal/process/promises:246
[vue-cli-service]           triggerUncaughtException(err, true /* fromPromise */);
[vue-cli-service]           ^
[vue-cli-service] RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 17254.
[vue-cli-service]     at /private/var/www/experiments/tutorial-photo-gallery-vue/node_modules/@vue/cli-plugin-typescript/node_modules/fork-ts-checker-webpack-plugin-v5/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
[vue-cli-service]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
[vue-cli-service]   code: undefined,
[vue-cli-service]   signal: undefined
[vue-cli-service] }
[vue-cli-service] Node.js v17.2.0

**Comment by brandyscarney** [comment]
Thanks for the issue! This project has since been migrated to Vite, so you shouldn't be receiving these errors. Please open a new issue if you run into any problems with the latest version of the app.
